### ISSUE TITLE
sqlalchemy-greenplum 0.2.0 in pypi

### ISSUE THREAD

**Issue by fuglaev** [PlaidCloud/sqlalchemy-greenplum#15]
Hello, may you bump version of package sqlalchemy-greenplum in pypi? Now, if use command pip install sqlalchemy-greenplum, we fetch old version of code, that conflict with sqlalchemy ^2.0…

**Comment by rad-pat** [comment]
We can do this, but may take a day or so. For now, can you try 
```
pip install sqlalchemy-greenplum@git+https://github.com/PlaidCloud/sqlalchemy-greenplum.git@master
```

**Comment by fuglaev** [comment]
We can wait, thank you very much! :)

**Comment by rad-pat** [comment]
I've not done a Pypi release for some time, but I think I've done it. Could you please confirm it works for you and I'll close the issue. Thanks

**Comment by fuglaev** [comment]
Everything works great! Thanks for the incredible speed!

**Comment by fuglaev** [comment]
May you also look at psycopg2-binary please..? For avoiding this failure https://github.com/vanna-ai/vanna/issues/166

I make PR for this
